create database db1;
use db1;
create table Employee(
ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
NAME VARCHAR(20),
ROLE VARCHAR(20),
insert_time DATE,
PRIMARY KEY (ID)
);


create database db2;
use db2;
CREATE TABLE `Department`(
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;

CREATE TABLE `Employee`(
 `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `NAME` varchar(100) NOT NULL,
 `ROLE` varchar(255) NOT NULL,
 `INSERT_TIME` date,
 PRIMARY KEY (`ID`) USING BTREE,
 CONSTRAINT `FK_ID` FOREIGN KEY (`ID`) REFERENCES `Department` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;